title: For Test
author: cnryb
email: cnryb@live.cn
description: > # this means to ignore newlines until "baseurl:"
  Only for test

# social links
twitter_username: cnryb
github_username:  cnryb

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
